# Generated by Django 5.2.7 on 2025-11-02 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_recipes', through='recipes.Favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
