# Generated by Django 5.2.7 on 2025-11-13 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_rating_recipes_rat_recipe__f5b1c5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created_at'], name='recipes_rec_created_57db65_idx'),
        ),
    ]
