# Generated by Django 5.2.7 on 2025-11-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_recipes_rec_created_57db65_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_created_57db65_idx',
        ),
    ]
